### PR TITLE
feat(watt): initial commit of incorporating the WATT invite runner

### PR DESCRIPTION
**Pull request by ajf214**
currently sending invites to sonofdiesel for testing
once everything is working properly, we can switch to sending to specific user

closes #247

### CODE REVIEW

**Comment by Snorrrlax** [comment]
Hi @wyantb, @MystK says he isn't able to check this out yet - would you be able to give the go ahead for merging?

**Comment by ajf214** [comment]
Thanks for all the comments @wyantb. I'll work on addressing them.  This is my first time working on an open source project, so apologies for what probably seem like obvious mistakes.

For your two main concerns:

1. I'm using firebase because that's the data store for WATT, and WATT needs to read the list of invites when a user clicks on an invite link to validate.  If it's a dealbreaker, I can figure something out.

2. It is a lot of reddit API calls for sure. Right now my code runs every 30 minutes. I can probably change it so it runs less frequently if this is a significant concern.

**Comment by wyantb** [comment]
Gotcha. If you're using firebase solely to interact with a 3rd party WATT system, that overrides my concern. No need to come up with completely new architecture there.

re: point 2...how does all this code run, anyway? I don't see it referenced from `index.js` or a new script in the `package.json` or anything referencing it. Could it be run as a separate daemon / bot with its own API key? In this sense it'd still be fine for it to be housed in this repo, I'm just wondering if it's possible to give it a separate execution model to ease this concern.

And no worries re: open source, you're doing great.

**Comment by MystK** [comment]
If it's in the module's folder, it automatically gets required.
________________________________

**Pull request closed without merging**
