### PR TITLE
docs(contributing): link to angular commit conventions used for commit messages

### PR DESCRIPTION
**Pull request by wyantb**
Per your request in #56.

Maybe someone else has documented the conventions somewhere else by now, but this is even the same link I use internally at work.  It's been around a while by now :)

### CODE REVIEW

**Comment by MystK** [comment]
Yes at work, we follow something similar also. We follow the Angular commit style over here: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md Maybe someone can make a PR adapting those guidelines to our repo.

**Comment by MystK** [comment]
Oh, didn't even know this was a PR. Thanks!

**Comment by roastchicken** [comment]
Are we still using these conventions? Only three out of the eleven commits made since this was added to the README have followed this convention for the format of their commit message. Maybe we should remove it from the README if we aren't using it anymore?

**Comment by roastchicken** [comment]
@MystK any word on whether you want to continue using Angular's conventions?

**Comment by MystK** [comment]
Yes. This is so weird. I reply in email but it doesn't make it here. I will retype what I said in the email.

Yes it is still in use. I’d like to follow a contribution format but this isn’t a huge open source project, and I wouldn’t decline a PR if the message didn’t follow the format. Can others weight their thoughts?

**Comment by roastchicken** [comment]
I don't know. On one hand, declining all PRs with commits that don't follow the conventions is a bit harsh and will likely mean less contributions because people are lazy. On the other hand, we have conventions for a reason so only using them on some commits seems pointless. I lean more towards requiring adherence to the conventions.

I read an article a while back about how to change commits in PRs instead of having to ask the contributor to do it. I'll try to find it again, but that would also up your work load @MystK.

**Comment by wyantb** [comment]
Some of the culprits (i.e. my multi-commit PRs) seem to be just squashed commits that individually meet the standards.  Instituting manual / real merges could help increase the conformance.

Otherwise, they're guidelines, not hard rules.  MystK can do what he feels is reasonable here, whether that's getting harsh about the rule, accepting commits whether or not they meet them, rebasing commits to meet the standards, etc.  NBD either way.

Aside: yes, MystK, I had the same thing happen, where responses to the email chain didn't post here.  Unfortunate...

**Comment by MystK** [comment]
Yes it is still in use. I’d like to follow a contribution format but this isn’t a huge open source project, and I wouldn’t decline a PR is the message didn’t follow the format. Can others weight their thoughts?

**Comment by wyantb** [comment]
Half the culprits (i.e. my multi-commit PRs) seem to be just squashed
commits that individually meet the standards.  Instituting manual / real
merges could help increase the conformance.

Otherwise, they're guidelines, not hard rules.  MystK can do what he feels
is reasonable here, whether that's getting harsh about the rule, accepting
commits whether or not they meet them, rebasing commits to meet the
standards, etc.  NBD either way.

Brian Wyant (Phone)

**Pull request merged**
