### PR TITLE
Some minor changes but I didn't want to get too far ahead.

### PR DESCRIPTION
**Pull request by stedop**
Added snoowrap to package.json and .idea folder to .gitignore (to ignore webstorm folder)

Added semi-colons to lines.

Started to add comments to server.js and added 'use strict' to the top

 Hit a snag with the comments, waiting for clarification but will move on to implementing snoowrap.

### CODE REVIEW

**Comment by MystK** [comment]
Thanks. Honestly the diff looks pretty freaky because all lines are changed. I don't have time to review everything, so I'll bring it in and run it on dev for a few days to see if there are any issues. Thanks

**Comment by MystK** [comment]
Hey there. It's causing a ton of eslint errors. 

image

I'm going to have to revert this commit until the eslint errors are resolved. We're using the airbnb eslint file. I'd like to keep it that way, but I'm open to discussion on why it's a good idea to change.

**Comment by MystK** [comment]
You'll most likely have to download the eslint plugin for Webstorm so you can see the errors like I do.

Regarding the semi colons, I overrode the airbnb semi colon rule. I'm happy to remove that rule and add semi colons. 👍 

On the 4 spaces vs 2, I'm more opinionated towards the 2 spaces, especially since it's adopted by airbnb. If it really bothers you that much, though, I'd be cool with 4 spaces too.

**Comment by stedop** [comment]
@MystK 

>You'll most likely have to download the eslint plugin for Webstorm so you can see the errors like I do.

I'll do that, thats for the info.

> Regarding the semi colons, I overrode the airbnb semi colon rule. I'm happy to remove that rule and add semi colons.

Honestly it's a hangover from when I was taught in pascal(!!) and php but it also makes some sense to me. I'll probably just do it as I go without thinking.

>On the 4 spaces vs 2, I'm more opinionated towards the 2 spaces, especially since it's adopted by airbnb. If it really bothers you that much, though, I'd be cool with 4 spaces too.
I'm easy with 2 spaces, I didn't even give it a thought so I'll change my webstorm settings on that, what's the point changing everyone else :+1:

**Comment by MystK** [comment]
Thanks and I'm glad we were able to comprise on a solution ;)

Get Outlook for iOS<https://aka.ms/o0ukef>




On Sun, Oct 9, 2016 at 4:41 AM -0700, "Stephen Dop" <notifications@github.com<mailto:notifications@github.com>> wrote:


@MystK<https://github.com/MystK>

You'll most likely have to download the eslint plugin for Webstorm so you can see the errors like I do.

I'll do that, thats for the info.

Regarding the semi colons, I overrode the airbnb semi colon rule. I'm happy to remove that rule and add semi colons.

Honestly it's a hangover from when I was taught in pascal(!!) and php but it also makes some sense to me. I'll probably just do it as I go without thinking.

On the 4 spaces vs 2, I'm more opinionated towards the 2 spaces, especially since it's adopted by airbnb. If it really bothers you that much, though, I'd be cool with 4 spaces too.
I'm easy with 2 spaces, I didn't even give it a thought so I'll change my webstorm settings on that, what's the point changing everyone else ?

-

**Comment by stedop** [comment]
I haven't changed any logic at this point so I don't think there will be a
massive problem but still absolutely worth testing

**Comment by roastchicken** [comment]
I just want to point out that it's usually a good idea to have atomic commits, i.e. one commit per change. Your original commit seems to be doing three or four different things, and as @MystK said that makes it hard to review because there are just so many lines changed (although that is probably mainly caused by the differing indentation).

**Comment by Snorrrlax** [comment]
@stedop @mystk any update on this?

**Comment by MystK** [comment]
No update from me.

**Comment by Snorrrlax** [comment]
@stedop hi, are you still able to help us here at all?

**Pull request merged**
