### PR TITLE
Update format of confirmation comment

### PR DESCRIPTION
**Pull request by roastchicken**
This pull request changes the confirmation comment to match the new format specified by Snorrlax in #32.

I haven't tested this (not sure how to) and I'm a bit of a javascript beginner, so I make no guarantees that this will work. I've done my best to make sure there are no syntax errors, but I may have missed something.

### CODE REVIEW

**Comment by MystK** [comment]
Thanks for the first ever PR! 👍 Let me go ahead and test this.

**Comment by MystK** [comment]
Also, if you could do a `git commit --amend` and update your commit to reference the ticket number and lower case the commit message.

Like this: `#37: update format of confirmation comment`

**Comment by roastchicken** [comment]
Do you want me to reference the issue, or the pull request?

#32 is the issue, #37 is this pull request.

**Comment by MystK** [comment]
yes thanks for that! The issue. :)

**Comment by MystK** [comment]
As a note, to test it I have a CMV dev subreddit and run the bot on my machine with my own credentials.

https://www.reddit.com/r/changemyviewdb3dev

**Comment by roastchicken** [comment]
I was just about to ask how you tested it.

I tried `git commit --amend` and then `git push --force` but for some reason it just replaced the main commit message with the body. Am I doing something wrong?

**Comment by MystK** [comment]
Looks good!

image

Pending commit message amend and QA approval by @Snorrrlax to approve.

After I will merge this PR and update DB3 production. :)

Thanks again man for the PR. 👍

**Comment by MystK** [comment]
Yes I'm pretty sure I know what's wrong. It's because # is the character to comment out items. We'll have to Google how to escape the # character.

**Comment by MystK** [comment]
http://stackoverflow.com/questions/2788092/start-a-git-commit-message-with-a-hashmark

For me personally, I use an IDE so I don't have the issue

**Comment by roastchicken** [comment]
Ah, that makes sense that it would comment it out.

**Comment by roastchicken** [comment]
After a minor incident where all of the normal comments in the amend prompt were added to the commit message (I guess git isn't smart enough to remove those when you change the cleanup), everything looks to be good.

**Comment by MystK** [comment]
Pending review by @Snorrrlax

**Comment by roastchicken** [comment]
After checking out the testing subreddit, it appears I overlooked something. DeltaBot thinks its own comment is an attempt to give someone a delta due to the delta symbol being in the message.

https://www.reddit.com/r/changemyviewDB3Dev/comments/502e1i/test/d86gaxb

I'm not sure the best course of action here. The most logical option I can think of would be to not attempt to award deltas based on comments made by DeltaBot, but you two may be able to come up with better ideas.

**Comment by MystK** [comment]
haha, glad you caught that. Would you be able to include changes to NOT check deltabot's own message?

You'll have to add it in the verifyThenAward function.

Something like
`
if (author === botUsername) return true
`

**Comment by MystK** [comment]
If you have questions about setting up your dev env, please message me. I on your website that you prefer Steam. 

http://steamcommunity.com/id/mystk/

**Comment by roastchicken** [comment]
I unfortunately don't have any more time tonight to work on this. I'll try
to check it out first thing in the morning.

**Comment by Snorrrlax** [comment]
Thank you! Once someone fixes that problem with DeltaBot's own deltas we should go ahead with this. 

Since you've written the code to find someone's total delta score, does that make the Deltaboard formatting issue easier?

**Comment by roastchicken** [comment]
I didn't actually write the code to find the number of deltas someone has. That function was already there because after a delta is awarded the flair must be updated, so the total number of deltas has to be fetched. I just moved it up a few lines so I could use the variable in the replacement code.

I'll take a look at #31 and see what I can do.

**Comment by roastchicken** [comment]
I added some code that I believe should prevent DeltaBot from trying to process its own comments.

**Comment by Snorrrlax** [comment]
Great, we'll let MystK test it and then merge.

**Comment by roastchicken** [comment]
@MystK is the bot for [/r/changemyviewDB3Dev/](https://www.reddit.com/r/changemyviewDB3Dev/ always running? I tried commenting in order to test, but it doesn't seem to be working. I guess it wouldn't automatically update anyways, so I couldn't test it even if it is running.

I'll try to set up my own testing environment.

**Comment by MystK** [comment]
Hi @roastchicken, sorry it's not always up. I just use it as a playground for when I run DB3 on my machine. If you need up setting up an env, please contact me! :)

**Comment by roastchicken** [comment]
Ok, that makes sense. Could you test this commit now that I've added the check for `author === botUsername`?

**Comment by MystK** [comment]
Looks good. Production has been updated. I will monitor for a few hours. Thanks again!

**Comment by roastchicken** [comment]
Ok, cool. Hope it doesn't run into any more bugs.

**Comment by MystK** [comment]
Small issue which didn't cause any issues other than logging.

https://github.com/MystK/delta-bot-three/commit/c5f716cd4df385053fafc5bf6a1bad65629201e9

I made a commit to fix and it's all set

**Pull request merged**
