### PR TITLE
#207 use DB for deltalog/stickComment reliability & de-duplication & related tweaks

### PR DESCRIPTION
**Pull request by wyantb**
This is an attempt to fix both #207 and #217 

Tested this out in https://www.reddit.com/r/db3_wyantb/comments/7ojvdi/cmv_this_is_a_test_and_only_a_test_please_ignore/ - I got up to having 3 delta comments in the post, then shutdown the bot instance that was running, made the 4th comment & award, then restarted the bot...and it updated the existing sticky comment with a link to the DeltaLog post it had made earlier. Good stuff. Since that's all my tweaks are related to, I didn't really test anything outside of this area.

You can also see that the old deltalog storage method, https://www.reddit.com/r/db3_wyantb/wiki/internal , is empty.

### CODE REVIEW

**Comment by Snorrrlax** [comment]
Thanks @wyantb! Really appreciate it. 

Great to see more progress on DeltaBot - some of these issues are still bothering us daily on the subreddit.

**Comment by wyantb** [comment]
Got it. Do you have a prioritized list anywhere of what types of issues you're getting hit the most by? Bugs-wise.

**Comment by Snorrrlax** [comment]
I don't have an up-to-date priority list, simply because I'm happy with anything being worked on, but it might be something like this:

#221 happens every now and then, but that was one of the worst cases. 
#198 happens every month.
#184 has happened a few times.
Do you know if #204 was solved? I haven't seen this since.  
#140 is quite important, as is #215.

Thoughts?

**Comment by wyantb** [comment]
I've never looked at 198, could be a relatively hard one to fix. For 221/184 I'm thinking we might want to start leveraging this DB work, but the DB should be tested in a live scenario first (i.e. let's merge and deploy this PR). Same with 204 (I don't think any code changes have been made for this, I'm just guessing that double posts are rare).

I think 140 would be pretty practical to implement (assuming I find another good chunk of time to work on this >.>)

**Comment by Snorrrlax** [comment]
#198 is arguably the most frustrating as it renders the monthly deltaboard useless towards the end of the month - which isn't good since we draw a lot of attention to it. But as I understand it, you haven't worked on the deltaboard side of things before, so you might prefer @MystK or @RaoulMeyer dealt with it (I don't believe they have plans to at the moment).

It would be equally great to have bug-free DeltaBot comments/score-keeping, though!

**Comment by MystK** [comment]
I haven't looked at #198 yet but I feel like it should be easy to fix

**Comment by MystK** [comment]
wow @wyantb this is great. I would have thought adding a database would be a much more grueling task!!!

**Comment by Snorrrlax** [comment]
@MystK could you work on #198 then? When you have time after you've reviewed and pushed this PR, of course.

**Comment by MystK** [comment]
We need to upgrade our Ramnode server before bringing this in right @wyantb?

**Comment by wyantb** [comment]
Yup, don't do this without the upgrade.

**Comment by MystK** [comment]
rebased and merged to master and staging

**Comment by MystK** [comment]
@wyantb something funky is happening on the install of level. It looks like it's failing on linux but fine on windows. I'm exploring further but did you happen to have any insight on this?

**Comment by MystK** [comment]
for documentation purposes I followed the GCC part of the link below

https://stackoverflow.com/questions/33762854/updating-gcc-on-centos-6-2/33764262#33764262

I rooted and ran the commands then also exported the variables on where the user is ran

**Comment by wyantb** [comment]
To clarify - based on your second comment, you were able to go through with the install after all, right?

**Comment by MystK** [comment]
Yup got everything working and deployed to staging. :)
________________________________

**Comment by MystK** [comment]
for reference I also had to do this to prevent building every time

https://stackoverflow.com/questions/35616650/how-to-upgrade-glibc-from-version-2-12-to-2-14-on-centos

**Pull request merged**
