### PR TITLE
Travis integration

### PR DESCRIPTION
**Pull request by wyantb**
Per my comments in #52.  Someone with access to the repo settings would need to enable the webhook (see https://travis-ci.org/getting_started ), but after that every push should be covered.  You can login to travis with your github, and it's free for OSS projects, so I figure it fits pretty well overall.  By default, travis runs `npm test` for node projects ( https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Default-Test-Script ) which fits us well, at least running eslint on pull requests.  Should be trivial after that to link to the status icon on the readme, etc, I figure.  Then step two someone can figure out uploading artifacts ( https://docs.travis-ci.com/user/uploading-artifacts/ ) but running eslint on requests alone is probably worth it already.

### CODE REVIEW

**Comment by MystK** [comment]
Hello, I've love to give you access to manage CI? Is that cool?

**Comment by wyantb** [comment]
Sure.  For any changes of worth (outside of readme, CI setup) I'll stick to pull requests anyway.

**Comment by MystK** [comment]
Thanks! Added

**Comment by wyantb** [comment]
Hmm.  Getting push access didn't give me rights to edit the settings of the repo.  On my fork, there's a "Settings" tab (after wiki/pulse/graphs) that I used to setup the integration that I still don't see here.

**Comment by MystK** [comment]
Howdy I think I did it. Now that you're a collaborator, it would be great if you could take a look at the issues and assign some to yourself.

**Comment by wyantb** [comment]
Well, time is the best judge for that :-)

These smaller issues have been convenient considering the spare time I
have.  Once some of the bigger proposed refactors like snoowrap etc work
themselves out one way or another, I'll take another look.  Maybe the
r/deltalog idea or some of the one-off scripts.

Brian Wyant (Phone)

On Oct 15, 2016 11:22 AM, "Antoine Pham" <notifications@github.com> wrote:

Howdy I think I did it. Now that you're a collaborator, it would be great
if you could take a look at the issues and assign some to yourself.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/MystK/delta-bot-three/pull/62#issuecomment-253990655>,
or mute the thread

**Pull request merged**
