### PR TITLE
style(i18n): More updates to DeltaBot comments

### PR DESCRIPTION
**Pull request by Snorrrlax**
Apologies, I was making some more changes to my last pull request just as you merged it :P

### CODE REVIEW

**Comment by Snorrrlax** [comment]
Okay that really is me done for now!

**Comment by Snorrrlax** [comment]
I want to test out this format (with the line). May change it back though.

**Comment by MystK** [comment]
Pushed to staging. Will be deployed in a few minutes. Please check it out and give a thumbs up to deploy to production.

**Comment by Snorrrlax** [comment]
Good to go!

**Comment by MystK** [comment]
released!

**Pull request merged**
